console.log("- Serveur: Serveur prêt! Actuellement en écoute de l'adresse 174.98.243.13 sur le port TCP 8356.")
console.log("- Client: Demande de connexion sortante créée par l'utilisateur: 174.98.243.13:8356 ; Protocole choisi: TCP.")
console.log("- Client: Début de la demande de connection TCP à 174.98.243.13:8356... SYN avec numéro de séquence de départ aléatoire envoyé. Numéro de séquence SYN: 10856.")
console.log("- Client: Attente de la réponse de 174.98.243.13:8356..")
console.log("- Serveur: Réception d'une demande de connexion entrante! Protocole: TCP - Port: 8356. SYN: 10856. Reconnaissance et acceptation de la demande..")
console.log("- Serveur: Génération de la réponse.. SYN d'origine: 10856 - ACK de réponse: SYN+1: 10857. Génération d'un SYN local aléatoire pour cette communication.. 751.")
console.log("- Serveur: Autorisation de connexion envoyée! SYN: 751 - ACK: 10857.")
console.log("- Serveur: Attente de la réponse du client..")
console.log("- Client: Communication entrante de 174.98.243.13:8356 reçue! ACK détecté, ACK: 10857 - Correspond avec la requête précédemment envoyée avec le SYN originel 10856 (ACK-1). Autorisation de connexion obtenue.")
console.log("- Client: Génération de la reconnaissance de la demande.. SYN d'origine de la réponse: 751. ACK de réponse: SYN+1: 752.")
console.log("- Client: Réponse envoyée! ACK: 752.")
console.log("- Réalitax, Clarificateur des faux scénarios: Dans une situation réelle, le serveur aurait probablement envoyé une autre requête avec le SYN 10857+1 afin de continuer la communication avec le client, mais puisque ce scénario à accomplit le but de son existence, il peut arriver à sa fin de manière plus simple.")
